#include <Layout/StateSchema.h>
#include <vendor/tinyxml2/tinyxml2.h>

#include <filesystem>
#include <fstream>
#include <sstream>

namespace RDA::Layout {

	namespace {
		bool typeFromElement(const char* name, StateType& out) {
			const std::string element = name ? name : "";
			if (element == "number") { out = StateType::Number; return true; }
			if (element == "bool")   { out = StateType::Bool;   return true; }
			if (element == "text")   { out = StateType::Text;   return true; }
			return false;
		}

		// "count" -> "setCount". Only the first letter moves; a name already capitalised
		// keeps its shape.
		std::string setterName(const std::string& field) {
			std::string out = "set" + field;
			if (out.size() > 3 && out[3] >= 'a' && out[3] <= 'z') out[3] -= 32;
			return out;
		}

		// The value as C++ writes it, and as TypeScript reads it.
		std::string cppLiteral(const StateField& field) {
			switch (field.type) {
			case StateType::Number: {
				// Spelled as a double on purpose. `define("count", 0)` would be ambiguous
				// between the number and boolean overloads, and the error it produces
				// points at generated code nobody wrote.
				if (field.value.empty()) return "0.0";
				const bool alreadyReal = field.value.find('.') != std::string::npos ||
				                         field.value.find('e') != std::string::npos ||
				                         field.value.find('E') != std::string::npos;
				return alreadyReal ? field.value : field.value + ".0";
			}
			case StateType::Bool:
				return field.value == "true" || field.value == "1" ? "true" : "false";
			case StateType::Text:
				return "std::string_view(\"" + field.value + "\")";
			}
			return "0.0";
		}

		const char* cppType(StateType type) {
			switch (type) {
			case StateType::Number: return "double";
			case StateType::Bool:   return "bool";
			case StateType::Text:   return "std::string_view";
			}
			return "double";
		}

		const char* readerCall(StateType type) {
			switch (type) {
			case StateType::Number: return "number";
			case StateType::Bool:   return "boolean";
			case StateType::Text:   return "text";
			}
			return "number";
		}
	}

	StateSchema loadStateSchema(const std::string& path) {
		StateSchema schema;
		schema.source = path;

		tinyxml2::XMLDocument document;
		if (document.LoadFile(path.c_str()) != tinyxml2::XML_SUCCESS) {
			schema.error = "cannot read " + path;
			return schema;
		}

		const tinyxml2::XMLElement* root = document.FirstChildElement("state");
		if (!root) {
			schema.error = path + " has no <state> element";
			return schema;
		}

		for (const tinyxml2::XMLElement* entry = root->FirstChildElement();
		     entry; entry = entry->NextSiblingElement()) {
			StateField field;
			if (!typeFromElement(entry->Name(), field.type)) {
				schema.error = std::string("unknown state type <") +
				               (entry->Name() ? entry->Name() : "?") +
				               ">; expected <number>, <bool> or <text>";
				return schema;
			}
			const char* name = entry->Attribute("name");
			if (!name || !*name) {
				schema.error = "a state entry has no name";
				return schema;
			}
			field.name = name;
			if (const char* value = entry->Attribute("value")) field.value = value;
			if (const char* doc = entry->Attribute("doc")) field.doc = doc;

			for (const StateField& existing : schema.fields) {
				if (existing.name == field.name) {
					schema.error = "state '" + field.name + "' is declared twice";
					return schema;
				}
			}
			schema.fields.push_back(std::move(field));
		}

		schema.ok = true;
		return schema;
	}

	bool emitStateHeader(const StateSchema& schema, const std::string& outputPath,
	                     std::string& error) {
		std::ostringstream out;
		out << "// Generated by `rda state` from " << schema.source << ". Do not edit.\n"
		       "//\n"
		       "// Declares the signals this application's interface is written against, and\n"
		       "// gives typed access to them. The same declaration produced the TypeScript a\n"
		       "// layout is checked against, so a name that exists on one side exists on both.\n"
		       "#pragma once\n"
		       "#include <Core/Signals.h>\n"
		       "#include <string_view>\n\n"
		       "namespace RDA::State {\n\n"
		       "\t// Filled by define(). Held rather than looked up, so reading a signal is an\n"
		       "\t// array index instead of a hash of its name.\n"
		       "\tstruct Ids {\n";
		for (const StateField& field : schema.fields) {
			out << "\t\tuint32_t " << field.name << " = kNoSignal;\n";
		}
		out << "\t};\n\n"
		       "\tinline Ids& ids() {\n"
		       "\t\tstatic Ids table;\n"
		       "\t\treturn table;\n"
		       "\t}\n\n"
		       "\t// Call once, before a layout is instantiated: a binding resolves the signals\n"
		       "\t// it reads when it is created, and one that does not exist yet is guessed at.\n"
		       "\tinline void define() {\n";
		for (const StateField& field : schema.fields) {
			out << "\t\tids()." << field.name << " = signals().define(\"" << field.name
			    << "\", " << cppLiteral(field) << ");\n";
		}
		out << "\t}\n";

		for (const StateField& field : schema.fields) {
			out << "\n";
			if (!field.doc.empty()) out << "\t/** " << field.doc << " */\n";
			out << "\tinline " << cppType(field.type) << " " << field.name << "() {\n"
			    << "\t\treturn signals()." << readerCall(field.type) << "(ids()." << field.name << ");\n"
			    << "\t}\n"
			    << "\tinline void " << setterName(field.name) << "(" << cppType(field.type)
			    << " value) {\n"
			    << "\t\tsignals().set(ids()." << field.name << ", value);\n"
			    << "\t}\n";
		}

		out << "}\n";

		const std::string text = out.str();

		// A generated header usually lands in a build directory that does not exist
		// yet, so making it is part of writing the file rather than the caller's job.
		std::error_code ec;
		const std::filesystem::path parent = std::filesystem::path(outputPath).parent_path();
		if (!parent.empty()) std::filesystem::create_directories(parent, ec);

		std::ofstream file(outputPath, std::ios::trunc);
		if (!file || !file.write(text.data(), static_cast<std::streamsize>(text.size()))) {
			error = "cannot write " + outputPath;
			return false;
		}
		return true;
	}
}
