#include <Layout/TypeEmitter.h>
#include <Layout/WidgetSchema.h>
#include <vendor/tinyxml2/tinyxml2.h>

#include <algorithm>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace RDA::Layout {

	namespace {
		using VariantsByElement = std::map<std::string, std::set<std::string>>;

		// Theme files name a variant per element: <button name="primary">. Collecting them
		// is the whole reason a theme is read here — it turns `variant` from "some string"
		// into the closed set this project actually defines.
		VariantsByElement readThemeVariants(const std::string& path, bool& found) {
			VariantsByElement variants;
			found = false;
			if (path.empty()) return variants;

			tinyxml2::XMLDocument document;
			if (document.LoadFile(path.c_str()) != tinyxml2::XML_SUCCESS) return variants;

			const tinyxml2::XMLElement* theme = document.FirstChildElement("theme");
			if (!theme) return variants;

			found = true;
			for (const tinyxml2::XMLElement* entry = theme->FirstChildElement();
			     entry; entry = entry->NextSiblingElement()) {
				const char* element = entry->Name();
				if (!element) continue;
				// A variant with no name= targets "default", which is always present anyway.
				if (const char* name = entry->Attribute("name")) {
					variants[element].insert(name);
				}
			}
			return variants;
		}

		std::string capitalise(std::string text) {
			if (!text.empty() && text[0] >= 'a' && text[0] <= 'z') text[0] -= 32;
			return text;
		}

		std::string variantTypeName(const std::string& element) {
			return "Rda" + capitalise(element) + "Variant";
		}

		// "line|document|code" -> "\"line\" | \"document\" | \"code\""
		std::string unionFromList(const char* values) {
			std::string out;
			std::string word;
			std::istringstream stream(values ? values : "");
			while (std::getline(stream, word, '|')) {
				if (word.empty()) continue;
				if (!out.empty()) out += " | ";
				out += "\"" + word + "\"";
			}
			return out.empty() ? "string" : out;
		}

		std::string typeExpression(const PropDesc& prop) {
			switch (prop.type) {
			case PropType::String:  return "string";
			case PropType::Number:  return "number";
			case PropType::Bool:    return "boolean";
			case PropType::Size:    return "RdaSize";
			case PropType::Enum:    return unionFromList(prop.values);
			case PropType::Variant:
				return variantTypeName(prop.values ? prop.values : "");
			}
			return "unknown";
		}

		void writeProp(std::ostream& out, const PropDesc& prop, const char* indent) {
			if (prop.doc && *prop.doc) out << indent << "/** " << prop.doc << " */\n";
			out << indent << prop.name << "?: " << typeExpression(prop) << ";\n";
		}
	}

	TypesResult emitTypeDefinitions(const std::string& outputPath, const std::string& themePath) {
		TypesResult result;

		bool themeFound = false;
		const VariantsByElement variants = readThemeVariants(themePath, themeFound);

		size_t commonCount = 0;
		const PropDesc* common = commonProps(commonCount);
		size_t widgetCount = 0;
		const WidgetDesc* widgets = widgetSchema(widgetCount);

		std::ostringstream out;
		out << "// Generated by `rda types` from the widget schema in C++. Do not edit.\n"
		       "//\n"
		       "// Every element and property below is declared once, in\n"
		       "// RendeerAlpha/src/Layout/WidgetSchema.cpp, and applied by the same table the\n"
		       "// loader reads. If something is missing here it is missing at runtime too,\n"
		       "// which is the point of generating it rather than writing it.\n";
		if (themeFound) {
			out << "//\n// Variant unions come from: " << themePath << "\n";
		} else {
			out << "//\n// No theme was read, so variants are plain strings. Pass a theme file to\n"
			       "// `rda types` to have them checked against the variants it defines.\n";
		}
		out << "\n"
		       "/** A number of pixels, or a word a layout container understands. */\n"
		       "type RdaSize = number | \"content\" | \"fill\" | `fill:${number}`;\n\n";

		// One union per theme element that a `variant` prop points at, so a button cannot
		// be given a text field's variant by accident.
		std::set<std::string> elementsNeeded;
		for (size_t w = 0; w < widgetCount; ++w) {
			for (size_t p = 0; p < widgets[w].propCount; ++p) {
				const PropDesc& prop = widgets[w].props[p];
				if (prop.type == PropType::Variant && prop.values) elementsNeeded.insert(prop.values);
			}
		}
		for (const std::string& element : elementsNeeded) {
			out << "type " << variantTypeName(element) << " = ";
			const auto found = variants.find(element);
			if (!themeFound || found == variants.end() || found->second.empty()) {
				out << "string;\n";
			} else {
				out << "\"default\"";
				for (const std::string& name : found->second) {
					if (name == "default") continue;
					out << " | \"" << name << "\"";
					++result.variantCount;
				}
				out << ";\n";
			}
		}

		out << "\n/** Accepted by every element. */\ninterface RdaCommonProps {\n";
		for (size_t i = 0; i < commonCount; ++i) writeProp(out, common[i], "\t");
		out << "}\n\n";

		// The JSX factory itself. esbuild rewrites <panel/> into a call to this, so a type
		// checker needs it in scope or every element is an undefined name. The engine
		// supplies the implementation at compile time; nothing calls it at runtime.
		out << "/** The JSX factory. Rewritten into by esbuild; implemented by the layout compiler. */\n"
		       "declare function h(\n"
		       "\ttype: string,\n"
		       "\tprops: Record<string, unknown> | null,\n"
		       "\t...children: unknown[]\n"
		       "): JSX.Element;\n\n";

		out << "declare namespace JSX {\n"
		       "\t/** What an element expression evaluates to. Opaque on purpose. */\n"
		       "\tinterface Element {}\n\n"
		       "\tinterface IntrinsicElements {\n";
		for (size_t w = 0; w < widgetCount; ++w) {
			const WidgetDesc& widget = widgets[w];
			if (widget.doc && *widget.doc) out << "\t\t/** " << widget.doc << " */\n";
			out << "\t\t" << widget.name << ": RdaCommonProps";
			if (widget.propCount == 0) {
				out << ";\n";
				continue;
			}
			out << " & {\n";
			for (size_t p = 0; p < widget.propCount; ++p) writeProp(out, widget.props[p], "\t\t\t");
			out << "\t\t};\n";
		}
		out << "\t}\n}\n";

		const std::string text = out.str();
		std::ofstream file(outputPath, std::ios::trunc);
		if (!file || !file.write(text.data(), static_cast<std::streamsize>(text.size()))) {
			result.error = "cannot write " + outputPath;
			return result;
		}

		result.ok          = true;
		result.widgetCount = widgetCount;
		result.byteSize    = text.size();
		return result;
	}
}
