#include <Layout/TypeEmitter.h>
#include <Layout/StateSchema.h>
#include <Layout/ThemeCompiler.h>
#include <Layout/WidgetSchema.h>

#include <algorithm>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace RDA::Layout {

	namespace {
		using VariantsByElement = std::map<std::string, std::set<std::string>>;

		// Compiling the theme is how its variants are known. The alternative -- a second
		// reader that looks for names without evaluating -- is a second answer to the same
		// question, and the two would disagree the first time anyone used a helper.
		VariantsByElement readThemeVariants(const std::string& path, bool& found, std::string& error) {
			VariantsByElement variants;
			found = false;
			if (path.empty()) return variants;

			const ThemeCompileResult theme = compileTheme(path);
			if (!theme.ok) {
				error = theme.error;
				return variants;
			}
			found = true;
			for (const auto& entry : theme.variants) variants[entry.first].insert(entry.second);
			return variants;
		}

		std::string capitalise(std::string text) {
			if (!text.empty() && text[0] >= 'a' && text[0] <= 'z') text[0] -= 32;
			return text;
		}

		std::string variantTypeName(const std::string& element) {
			return "Rda" + capitalise(element) + "Variant";
		}

		// "line|document|code" -> "\"line\" | \"document\" | \"code\""
		std::string unionFromList(const char* values) {
			std::string out;
			std::string word;
			std::istringstream stream(values ? values : "");
			while (std::getline(stream, word, '|')) {
				if (word.empty()) continue;
				if (!out.empty()) out += " | ";
				out += "\"" + word + "\"";
			}
			return out.empty() ? "string" : out;
		}

		std::string typeExpression(const PropDesc& prop) {
			switch (prop.type) {
			case PropType::String:  return "string";
			case PropType::Number:  return "number";
			case PropType::Bool:    return "boolean";
			case PropType::Size:    return "RdaSize";
			case PropType::Enum:    return unionFromList(prop.values);
			case PropType::Variant:
				return variantTypeName(prop.values ? prop.values : "");
			case PropType::Event:
				return "RdaHandler";
			}
			return "unknown";
		}

		void writeProp(std::ostream& out, const PropDesc& prop, const char* indent) {
			if (prop.doc && *prop.doc) out << indent << "/** " << prop.doc << " */\n";
			out << indent << prop.name << "?: ";
			// Every value property accepts a binding as well as a constant, because the
			// compiler accepts one. A type that said otherwise would reject exactly the
			// code this pipeline exists for. Events are already thunks.
			if (prop.type == PropType::Event) out << "RdaHandler";
			else out << "RdaBound<" << typeExpression(prop) << ">";
			out << ";\n";
		}
	}

	TypesResult emitTypeDefinitions(const std::string& outputPath, const std::string& themePath,
	                                const std::string& statePath) {
		TypesResult result;

		bool themeFound = false;
		std::string themeError;
		const VariantsByElement variants = readThemeVariants(themePath, themeFound, themeError);
		if (!themePath.empty() && !themeFound) {
			result.error = "theme: " + themeError;
			return result;
		}
		const StateSchema state = statePath.empty() ? StateSchema{} : loadStateSchema(statePath);
		if (!statePath.empty() && !state.ok) {
			result.error = state.error;
			return result;
		}

		size_t commonCount = 0;
		const PropDesc* common = commonProps(commonCount);
		size_t widgetCount = 0;
		const WidgetDesc* widgets = widgetSchema(widgetCount);

		std::ostringstream out;
		out << "// Generated by `rda types` from the widget schema in C++. Do not edit.\n"
		       "//\n"
		       "// Every element and property below is declared once, in\n"
		       "// RendeerAlpha/src/Layout/WidgetSchema.cpp, and applied by the same table the\n"
		       "// loader reads. If something is missing here it is missing at runtime too,\n"
		       "// which is the point of generating it rather than writing it.\n";
		if (themeFound) {
			out << "//\n// Variant unions come from: " << themePath << "\n";
		} else {
			out << "//\n// No theme was read, so variants are plain strings. Pass a theme file to\n"
			       "// `rda types` to have them checked against the variants it defines.\n";
		}
		out << "\n"
		       "/** A number of pixels, or a word a layout container understands. */\n"
		       "type RdaSize = number | \"content\" | \"fill\" | `fill:${number}`;\n\n";

		out << "/**\n"
		       " * A property value: either a constant, or a binding that computes one.\n"
		       " *\n"
		       " * A binding is compiled to bytecode at build time, so it may read state and\n"
		       " * literals and nothing else -- not a call, and not a variable from the code\n"
		       " * around it.\n"
		       " */\n"
		       "type RdaBound<T> = T | (() => T);\n\n"
		       "/** An event handler. Compiled like a binding, and may write state. */\n"
		       "type RdaHandler = () => unknown;\n\n";

		// One union per theme element that a `variant` prop points at, so a button cannot
		// be given a text field variant by accident.
		std::set<std::string> elementsNeeded;
		for (size_t w = 0; w < widgetCount; ++w) {
			for (size_t p = 0; p < widgets[w].propCount; ++p) {
				const PropDesc& prop = widgets[w].props[p];
				if (prop.type == PropType::Variant && prop.values) elementsNeeded.insert(prop.values);
			}
		}
		for (const std::string& element : elementsNeeded) {
			out << "type " << variantTypeName(element) << " = ";
			const auto found = variants.find(element);
			if (!themeFound || found == variants.end() || found->second.empty()) {
				out << "string;\n";
			} else {
				out << "\"default\"";
				for (const std::string& name : found->second) {
					if (name == "default") continue;
					out << " | \"" << name << "\"";
					++result.variantCount;
				}
				out << ";\n";
			}
		}

		out << "\n/** Accepted by every element. */\ninterface RdaCommonProps {\n";
		for (size_t i = 0; i < commonCount; ++i) writeProp(out, common[i], "\t");
		out << "}\n\n";

		if (state.ok && !state.empty()) {
			out << "/**\n"
			       " * Application state, from " << statePath << ".\n"
			       " *\n"
			       " * The same declaration generated the C++ that defines these signals,\n"
			       " * so a name that type-checks here exists at runtime.\n"
			       " */\n"
			       "interface RdaState {\n";
			for (const StateField& field : state.fields) {
				if (!field.doc.empty()) out << "\t/** " << field.doc << " */\n";
				out << "\t" << field.name << ": ";
				switch (field.type) {
				case StateType::Number: out << "number"; break;
				case StateType::Bool:   out << "boolean"; break;
				case StateType::Text:   out << "string"; break;
				}
				out << ";\n";
				++result.stateCount;
			}
			out << "}\n\n"
			       "declare const state: RdaState;\n\n";
		} else {
			out << "/**\n"
			       " * Application state. A binding reads it as `state.<name>`.\n"
			       " *\n"
			       " * Loosely typed because no state declaration was given. Pass one to\n"
			       " * `rda types` and a misspelled signal becomes an error here rather than\n"
			       " * a warning when the layout loads.\n"
			       " */\n"
			       "declare const state: Record<string, any>;\n\n";
		}

		out << "/** The JSX factory. Rewritten into by esbuild; implemented by the layout compiler. */\n"
		       "declare function h(\n"
		       "\ttype: string,\n"
		       "\tprops: Record<string, unknown> | null,\n"
		       "\t...children: unknown[]\n"
		       "): JSX.Element;\n\n";

		out << "declare namespace JSX {\n"
		       "\t/** What an element expression evaluates to. Opaque on purpose. */\n"
		       "\tinterface Element {}\n\n"
		       "\tinterface IntrinsicElements {\n";
		for (size_t w = 0; w < widgetCount; ++w) {
			const WidgetDesc& widget = widgets[w];
			if (widget.doc && *widget.doc) out << "\t\t/** " << widget.doc << " */\n";
			out << "\t\t" << widget.name << ": RdaCommonProps";
			if (widget.propCount == 0) {
				out << ";\n";
				continue;
			}
			out << " & {\n";
			for (size_t p = 0; p < widget.propCount; ++p) writeProp(out, widget.props[p], "\t\t\t");
			out << "\t\t};\n";
		}
		out << "\t}\n}\n";

		const std::string text = out.str();
		std::ofstream file(outputPath, std::ios::trunc);
		if (!file || !file.write(text.data(), static_cast<std::streamsize>(text.size()))) {
			result.error = "cannot write " + outputPath;
			return result;
		}

		result.ok          = true;
		result.widgetCount = widgetCount;
		result.byteSize    = text.size();
		return result;
	}
}
