// Sandbox — the smallest complete RendeerAlpha application.
//
// This is the first file to read, and there is deliberately very little in it. The
// interface lives in res/layouts/hello.tsx; what it *does* lives there too, as bindings
// compiled to bytecode. All this program does is declare the state both sides agree on,
// and load the result.
//
//   res/state.xml       what the state is called, and what type it holds
//   res/layouts/*.tsx    what the interface is, and how it reacts
//   this file            load one, having declared the other
//
// The state is declared once, in XML, and the build generates both sides from it: the
// C++ below that defines the signals, and the TypeScript that hello.tsx is checked
// against. So a misspelling is a compile error on whichever side made it, rather than a
// signal that quietly holds zero forever.
//
// Nothing here searches the widget tree. In a Debug build the layout is watched, so
// editing hello.tsx while this is running rebuilds the interface -- and the state
// survives, because signals live out here rather than inside the thing being replaced.
// A Release build watches nothing and contains no compiler at all.
//
// Try this first: run it, click a button a few times, then edit a label in
// res/layouts/hello.tsx and save. The interface changes; the count does not.
#include <RendeerAlpha.h>
#include <Layout/Bindings.h>
#include <Layout/LayoutHost.h>
#include <Logger/Logger.h>

// Generated by the build from res/state.xml.
#include <RdaState.h>

#include <string>

namespace {

	// The blueprint is the copy beside the executable; that is what gets loaded, and
	// what a recompile overwrites.
	const std::string kLayoutBlueprint = "res/layouts/hello.rdab";

	// The source is the original in the project, not the copy. Only a development build
	// is told where that is -- see Sandbox/CMakeLists.txt.
#ifdef RDA_SANDBOX_SOURCE_DIR
	const std::string kLayoutSource = std::string(RDA_SANDBOX_SOURCE_DIR) + "/res/layouts/hello.tsx";
#else
	const std::string kLayoutSource;
#endif

	// Owns the interface and rebuilds it when its file changes.
	RDA::Layout::LayoutHost gInterface;

	void buildInterface() {
		// Every signal res/state.xml declares, with the types and initial values it gives
		// them. Before the layout, because a binding resolves what it reads when it is
		// created and one that does not exist yet is only guessed at.
		RDA::State::define();

		RDA::Gui& gui = getMainWindow()->gui();

		// The source path is only consulted where the build can compile one; a Release
		// build watches the blueprint and nothing else.
		if (!gInterface.open(gui.retained(), kLayoutBlueprint, kLayoutSource)) {
			RDA::Label* message = gui.retained().add<RDA::Label>("error",
				"No layout found - build again; the build compiles hello.tsx.");
			message->rect = { 20.0f, 20.0f, 0.0f, 0.0f };
			return;
		}

		RDA_LOG_INFO("sandbox: interface loaded, "
		             << gInterface.instance().bindingCount() << " bindings"
		             << (RDA::Layout::LayoutHost::canCompile() ? ", watching hello.tsx" : ""));
	}
}

int main() {
	RDA::AppConfig config;
	config.app.name = "Sandbox";
	config.app.appVersion = 1;

	config.gui.enabled = true;
	config.gui.themePath = "res/themes/sandbox.rdth";

	// Nothing animates, so frames are drawn only when something changes -- which now
	// includes a signal changing. An idle window costs effectively no CPU.
	config.redrawMode = RDA::RedrawMode::OnDemand;
	config.viewportMode = RDA::ViewportMode::Fullscreen;
	config.threadMode = RDA::ThreadMode::Caller;

	config.onStart = []() { buildInterface(); };

	// Checked here rather than in a callback: reloading restructures the widget tree, and
	// onUpdate runs after that tree has been walked for this frame.
	config.onUpdate = [](float) {
		if (gInterface.reloadIfChanged()) {
			RDA_LOG_INFO("sandbox: reloaded in " << gInterface.lastReloadMs() << " ms");
		}
	};
	// Released here rather than at process exit, so the bindings are gone while the
	// signal table they registered with is still alive.
	config.onShutdown = []() { gInterface = RDA::Layout::LayoutHost{}; };

	rendeerRun(config);
	return 0;
}
