// Generated by `rda types` from the widget schema in C++. Do not edit.
//
// Every element and property below is declared once, in
// RendeerAlpha/src/Layout/WidgetSchema.cpp, and applied by the same table the
// loader reads. If something is missing here it is missing at runtime too,
// which is the point of generating it rather than writing it.
//
// Variant unions come from: G:/Fisiere/ProiecteVS/RendeerAlpha/Sandbox/res/themes/sandbox.ts

/** A number of pixels, or a word a layout container understands. */
type RdaSize = number | "content" | "fill" | `fill:${number}`;

/**
 * A property value: either a constant, or a binding that computes one.
 *
 * A binding is compiled to bytecode at build time, so it may read state and
 * literals and nothing else -- not a call, and not a variable from the code
 * around it.
 */
type RdaBound<T> = T | (() => T);

/** An event handler. Compiled like a binding, and may write state. */
type RdaHandler = () => unknown;

type RdaButtonVariant = "default" | "danger" | "ghost" | "primary";
type RdaCheckboxVariant = "default" | "accent";
type RdaLabelVariant = "default" | "muted";
type RdaPanelVariant = string;
type RdaSliderVariant = "default" | "warm";
type RdaTextfieldVariant = "default" | "console-out" | "ide" | "ide-cpp" | "ide-js" | "notes";

/** Accepted by every element. */
interface RdaCommonProps {
	/** name for this node; the compiler turns it into a path, which is what hover and focus are keyed on */
	id?: RdaBound<string>;
	/** drawn and interactive when true */
	visible?: RdaBound<boolean>;
	/** how wide, when a layout container is deciding */
	width?: RdaBound<RdaSize>;
	/** how tall, when a layout container is deciding */
	height?: RdaBound<RdaSize>;
	/** lower bound on the resolved width */
	minWidth?: RdaBound<number>;
	/** upper bound on the resolved width */
	maxWidth?: RdaBound<number>;
	/** lower bound on the resolved height */
	minHeight?: RdaBound<number>;
	/** upper bound on the resolved height */
	maxHeight?: RdaBound<number>;
	/** left edge, relative to the parent's content origin */
	x?: RdaBound<number>;
	/** top edge, relative to the parent's content origin */
	y?: RdaBound<number>;
	/** width, when placed absolutely rather than laid out */
	w?: RdaBound<number>;
	/** height, when placed absolutely rather than laid out */
	h?: RdaBound<number>;
	/** distance kept from the parent's right edge when anchored to it */
	marginRight?: RdaBound<number>;
	/** distance kept from the parent's bottom edge when anchored to it */
	marginBottom?: RdaBound<number>;
	/** which parent edges this node follows */
	anchor?: RdaBound<"fill" | "stretchX" | "stretchY" | "bottomLeft" | "bottomRight">;
}

/**
 * Application state, from G:/Fisiere/ProiecteVS/RendeerAlpha/Sandbox/res/state.xml.
 *
 * The same declaration generated the C++ that defines these signals,
 * so a name that type-checks here exists at runtime.
 */
interface RdaState {
	/** how many times a button has been pressed */
	count: number;
	/** whether the arithmetic rows are shown */
	details: boolean;
}

declare const state: RdaState;

/** The JSX factory. Rewritten into by esbuild; implemented by the layout compiler. */
declare function h(
	type: string,
	props: Record<string, unknown> | null,
	...children: unknown[]
): JSX.Element;

declare namespace JSX {
	/** What an element expression evaluates to. Opaque on purpose. */
	interface Element {}

	interface IntrinsicElements {
		/** groups children without drawing anything */
		container: RdaCommonProps & {
			/** grouping node; draws nothing of its own */
			visible?: RdaBound<boolean>;
		};
		/** a framed background that clips its children */
		panel: RdaCommonProps & {
			/** theme variant to draw with */
			variant?: RdaBound<RdaPanelVariant>;
		};
		/** lays children out in a row or a column */
		stack: RdaCommonProps & {
			/** top to bottom when true, left to right when false */
			vertical?: RdaBound<boolean>;
			/** gap between children */
			spacing?: RdaBound<number>;
			/** inset around the whole row or column */
			padding?: RdaBound<number>;
		};
		/** a clipped window onto content taller than itself */
		scrollview: RdaCommonProps & {
			/** theme variant to draw with */
			variant?: RdaBound<RdaTextfieldVariant>;
			/** gap between stacked children */
			spacing?: RdaBound<number>;
			/** inset around the content */
			padding?: RdaBound<number>;
		};
		/** a draggable bar that resizes what is above it */
		splitter: RdaCommonProps & {
			/** a vertical bar dragged left and right when true */
			vertical?: RdaBound<boolean>;
			/** the size this splitter controls */
			value?: RdaBound<number>;
			/** smallest it will drag to */
			min?: RdaBound<number>;
			/** largest it will drag to */
			max?: RdaBound<number>;
		};
		/** draws the 3D scene */
		viewport: RdaCommonProps & {
			/** shows the scene; needs ViewportMode::Widget */
			visible?: RdaBound<boolean>;
		};
		/** a line of text */
		label: RdaCommonProps & {
			/** the text drawn */
			text?: RdaBound<string>;
			/** theme variant to draw with */
			variant?: RdaBound<RdaLabelVariant>;
		};
		/** a clickable button */
		button: RdaCommonProps & {
			/** the text drawn on it */
			text?: RdaBound<string>;
			/** theme variant to draw with */
			variant?: RdaBound<RdaButtonVariant>;
			/** runs on each completed click */
			onClick?: RdaHandler;
		};
		/** a labelled boolean toggle */
		checkbox: RdaCommonProps & {
			/** the text beside the box */
			label?: RdaBound<string>;
			/** ticked when true */
			value?: RdaBound<boolean>;
			/** theme variant to draw with */
			variant?: RdaBound<RdaCheckboxVariant>;
			/** runs when it is toggled */
			onChange?: RdaHandler;
		};
		/** a draggable value between two bounds */
		slider: RdaCommonProps & {
			/** where the knob starts */
			value?: RdaBound<number>;
			/** value at the left end */
			min?: RdaBound<number>;
			/** value at the right end */
			max?: RdaBound<number>;
			/** theme variant to draw with */
			variant?: RdaBound<RdaSliderVariant>;
			/** runs while it is dragged */
			onChange?: RdaHandler;
		};
		/** an editable text field */
		textfield: RdaCommonProps & {
			/** the contents */
			text?: RdaBound<string>;
			/** single line, a text area, or a code editor with a gutter */
			mode?: RdaBound<"line" | "document" | "code">;
			/** theme variant to draw with */
			variant?: RdaBound<RdaTextfieldVariant>;
		};
	}
}
