// Generated by `rda types` from the widget schema in C++. Do not edit.
//
// Every element and property below is declared once, in
// RendeerAlpha/src/Layout/WidgetSchema.cpp, and applied by the same table the
// loader reads. If something is missing here it is missing at runtime too,
// which is the point of generating it rather than writing it.
//
// Variant unions come from: RendeerAlpha/res/themes/sandbox.xml

/** A number of pixels, or a word a layout container understands. */
type RdaSize = number | "content" | "fill" | `fill:${number}`;

type RdaButtonVariant = "default" | "danger" | "ghost" | "primary";
type RdaCheckboxVariant = "default" | "accent";
type RdaLabelVariant = "default" | "muted";
type RdaPanelVariant = string;
type RdaSliderVariant = "default" | "warm";
type RdaTextfieldVariant = "default" | "console-out" | "ide" | "ide-cpp" | "ide-js" | "notes";

/** Accepted by every element. */
interface RdaCommonProps {
	/** name for this node; the compiler turns it into a path, which is what hover and focus are keyed on */
	id?: string;
	/** drawn and interactive when true */
	visible?: boolean;
	/** how wide, when a layout container is deciding */
	width?: RdaSize;
	/** how tall, when a layout container is deciding */
	height?: RdaSize;
	/** lower bound on the resolved width */
	minWidth?: number;
	/** upper bound on the resolved width */
	maxWidth?: number;
	/** lower bound on the resolved height */
	minHeight?: number;
	/** upper bound on the resolved height */
	maxHeight?: number;
	/** left edge, relative to the parent's content origin */
	x?: number;
	/** top edge, relative to the parent's content origin */
	y?: number;
	/** width, when placed absolutely rather than laid out */
	w?: number;
	/** height, when placed absolutely rather than laid out */
	h?: number;
	/** distance kept from the parent's right edge when anchored to it */
	marginRight?: number;
	/** distance kept from the parent's bottom edge when anchored to it */
	marginBottom?: number;
	/** which parent edges this node follows */
	anchor?: "fill" | "stretchX" | "stretchY" | "bottomLeft" | "bottomRight";
}

/** The JSX factory. Rewritten into by esbuild; implemented by the layout compiler. */
declare function h(
	type: string,
	props: Record<string, unknown> | null,
	...children: unknown[]
): JSX.Element;

declare namespace JSX {
	/** What an element expression evaluates to. Opaque on purpose. */
	interface Element {}

	interface IntrinsicElements {
		/** groups children without drawing anything */
		container: RdaCommonProps & {
			/** grouping node; draws nothing of its own */
			visible?: boolean;
		};
		/** a framed background that clips its children */
		panel: RdaCommonProps & {
			/** theme variant to draw with */
			variant?: RdaPanelVariant;
		};
		/** lays children out in a row or a column */
		stack: RdaCommonProps & {
			/** top to bottom when true, left to right when false */
			vertical?: boolean;
			/** gap between children */
			spacing?: number;
			/** inset around the whole row or column */
			padding?: number;
		};
		/** a clipped window onto content taller than itself */
		scrollview: RdaCommonProps & {
			/** theme variant to draw with */
			variant?: RdaTextfieldVariant;
			/** gap between stacked children */
			spacing?: number;
			/** inset around the content */
			padding?: number;
		};
		/** a draggable bar that resizes what is above it */
		splitter: RdaCommonProps & {
			/** a vertical bar dragged left and right when true */
			vertical?: boolean;
			/** the size this splitter controls */
			value?: number;
			/** smallest it will drag to */
			min?: number;
			/** largest it will drag to */
			max?: number;
		};
		/** draws the 3D scene */
		viewport: RdaCommonProps & {
			/** shows the scene; needs ViewportMode::Widget */
			visible?: boolean;
		};
		/** a line of text */
		label: RdaCommonProps & {
			/** the text drawn */
			text?: string;
			/** theme variant to draw with */
			variant?: RdaLabelVariant;
		};
		/** a clickable button */
		button: RdaCommonProps & {
			/** the text drawn on it */
			text?: string;
			/** theme variant to draw with */
			variant?: RdaButtonVariant;
		};
		/** a labelled boolean toggle */
		checkbox: RdaCommonProps & {
			/** the text beside the box */
			label?: string;
			/** ticked when true */
			value?: boolean;
			/** theme variant to draw with */
			variant?: RdaCheckboxVariant;
		};
		/** a draggable value between two bounds */
		slider: RdaCommonProps & {
			/** where the knob starts */
			value?: number;
			/** value at the left end */
			min?: number;
			/** value at the right end */
			max?: number;
			/** theme variant to draw with */
			variant?: RdaSliderVariant;
		};
		/** an editable text field */
		textfield: RdaCommonProps & {
			/** the contents */
			text?: string;
			/** single line, a text area, or a code editor with a gutter */
			mode?: "line" | "document" | "code";
			/** theme variant to draw with */
			variant?: RdaTextfieldVariant;
		};
	}
}
