"""rda -- write a RendeerAlpha backend in Python.

    import rda
    from state import State, Commands       # generated by `rda python`

    config = rda.StartupConfig()
    config.name = "My application"
    config.theme = "res/themes/app.rdth"

    @config.on_start
    def opened():
        rda.load_interface("res/layouts/home.rdab")
        State.count = 0

    @Commands.add_one
    def add_one():
        State.count += 1

    rda.init(config)
    rda.wait()

Python is a *backend* here, which is what the engine is for. The interface is a compiled
layout -- written in TSX, checked against a generated schema, styled by a theme, bound to
signals and animated by the engine. Python does not draw it; it loads it, writes the state
it reads, and answers the work it asks for. That is the same job C++ has, and the layout
cannot tell which of them is behind it.

There is no extension module to build. The engine is a shared library and this package is
a description of it, so `pip install` has nothing to compile and nothing to go wrong.

---- threading ----

`init()` starts the engine on a thread of its own and returns once it is up -- the window,
the renderer and your on_start all finished -- so the interpreter stays yours and the line
after it may write state. A REPL, a web server or a data pipeline can carry on while a
window is open. Call `wait()` when there is nothing left to do but let the window live.

Every call in this package is safe from any thread. The engine's state belongs to its loop
thread, so each call hands its work over and waits -- which costs a frame, and is the
right price for a backend. Handlers run on the loop thread; calls made from inside one are
free.
"""

from . import _engine
from ._engine import RdaError, bind_command, invoke, load

__all__ = [
    "StartupConfig", "RdaError", "Drawing",
    "init", "stop", "wait", "running", "load_interface", "bind_command", "invoke", "load",
    "open_routes", "set_transition_ms", "back", "forward",
    "can_go_back", "can_go_forward",
    "draw", "viewport_size", "set_theme",
    "set_title", "set_icon", "clipboard", "set_clipboard", "measure_text",
    "focus", "pick_folder", "pick_file", "dropped_files",
    "define_image", "define_image_pixels", "forget_image",
    "push_frame", "push_frame_pixels", "stream_wanted", "stream_counts", "close_stream",
    "define_effect", "apply_effect", "forget_effect", "read_frame",
]


class StartupConfig:
    """What the engine needs to start.

    The callbacks are decorators as well as attributes, because a handler reads better
    where it is written than in an assignment three lines further down:

        @config.on_start
        def opened():
            ...
    """

    __slots__ = ("name", "theme", "languages", "vsync", "font", "font_height",
                 "width", "height",
                 "icon", "decorated", "resizable", "maximized", "fullscreen",
                 "always_on_top", "transparent", "opacity",
                 "min_width", "min_height", "max_width", "max_height", "x", "y",
                 "_on_start", "_on_update", "_on_shutdown")

    def __init__(self):
        self.name = "RendeerAlpha"
        self.theme = ""       # a compiled .rdth; empty keeps the built-in look
        self.languages = ""   # res/themes/languages.xml, for syntax highlighting
        self.vsync = True
        self.font = ""        # a .ttf; empty keeps the engine's own
        self.font_height = 0  # pixels for body text; 0 keeps the default
        # The size the window opens at; 0 keeps the engine's default. Only the opening
        # size -- where the reader leaves it is read back through state.rda.
        self.width = 0
        self.height = 0

        # The picture the OS shows for the window -- the title bar, the alt-tab card,
        # the taskbar. A .png, or an .svg, which is drawn at every size an OS picks
        # from. Not the executable's icon: that one is built into the binary.
        self.icon = ""
        # The OS frame. False means your layout draws its own, and something in it wants
        # dragWindow or the window cannot be moved.
        self.decorated = True
        self.resizable = True
        self.maximized = False
        self.fullscreen = False
        self.always_on_top = False
        # A framebuffer with a real alpha channel, so a clear colour that is not opaque
        # lets the desktop through. Decided when the window is created and nowhere else.
        self.transparent = False
        self.opacity = 1.0
        # Bounds the reader cannot drag past; 0 on an axis means no bound there.
        self.min_width = 0
        self.min_height = 0
        self.max_width = 0
        self.max_height = 0
        # Where the top-left corner opens. None leaves it to the platform.
        self.x = None
        self.y = None
        self._on_start = None
        self._on_update = None
        self._on_shutdown = None

    def on_start(self, fn):
        """Once, after the window is up. Load the interface here."""
        self._on_start = fn
        return fn

    def on_update(self, fn):
        """Once per frame, before it is drawn. Takes the seconds since the last one."""
        self._on_update = fn
        return fn

    def on_shutdown(self, fn):
        """Once, after the loop ends."""
        self._on_shutdown = fn
        return fn


_config_handle = None


def init(config=None):
    """Starts the engine and returns once it is up.

    Up means the window, the renderer and your on_start have all finished -- so the line
    after this one may write state and expect it to exist. The engine itself runs on a
    thread of its own, which is why this returns at all.

    Raises RdaError if it did not start, or if on_start stopped it.
    """
    global _config_handle
    from . import _engine

    lib = _engine.load()
    config = config or StartupConfig()

    handle = lib.rda_config_new()
    if not handle:
        raise RdaError("cannot allocate a config")
    lib.rda_config_set_name(handle, str(config.name).encode("utf-8"))
    if config.theme:
        lib.rda_config_set_theme(handle, str(config.theme).encode("utf-8"))
    if config.languages:
        lib.rda_config_set_languages(handle, str(config.languages).encode("utf-8"))
    lib.rda_config_set_vsync(handle, 1 if config.vsync else 0)
    if config.width or config.height:
        lib.rda_config_set_size(handle, int(config.width), int(config.height))
    if config.font or config.font_height:
        lib.rda_config_set_font(handle, str(config.font).encode("utf-8"),
                                float(config.font_height))

    # How the window is dressed. Each one is sent only when it differs from the engine's
    # own default, so a config nobody touched makes no calls at all.
    if config.icon:
        lib.rda_config_set_icon(handle, str(config.icon).encode("utf-8"))
    if not config.decorated:
        lib.rda_config_set_decorated(handle, 0)
    if not config.resizable:
        lib.rda_config_set_resizable(handle, 0)
    if config.maximized:
        lib.rda_config_set_maximized(handle, 1)
    if config.fullscreen:
        lib.rda_config_set_fullscreen(handle, 1)
    if config.always_on_top:
        lib.rda_config_set_always_on_top(handle, 1)
    if config.transparent:
        lib.rda_config_set_transparent(handle, 1)
    if config.opacity != 1.0:
        lib.rda_config_set_opacity(handle, float(config.opacity))
    if config.min_width or config.min_height or config.max_width or config.max_height:
        lib.rda_config_set_size_limits(handle, int(config.min_width), int(config.min_height),
                                       int(config.max_width), int(config.max_height))
    if config.x is not None or config.y is not None:
        # An axis nobody set stays the platform's choice, which is not the same answer
        # as 0 -- that is a corner of the screen.
        unplaced = -2147483648
        lib.rda_config_set_position(handle,
                                    unplaced if config.x is None else int(config.x),
                                    unplaced if config.y is None else int(config.y))

    # Held for the life of the process for the same reason a command handler is: the
    # engine calls these long after this function has returned.
    # on_start is always registered, whether or not the application wanted one: it is
    # also where handlers bound at import time are applied, and they can only be applied
    # after the application has declared the commands they name.
    def _started(_user):
        if config._on_start:
            config._on_start()
        _engine.flush_pending()

    trampoline = _engine._Callback(_started)
    _engine._alive.append(trampoline)
    lib.rda_config_on_start(handle, trampoline, None)
    if config._on_update:
        trampoline = _engine._UpdateCallback(lambda dt, _user: config._on_update(dt))
        _engine._alive.append(trampoline)
        lib.rda_config_on_update(handle, trampoline, None)
    if config._on_shutdown:
        trampoline = _engine._Callback(lambda _user: config._on_shutdown())
        _engine._alive.append(trampoline)
        lib.rda_config_on_shutdown(handle, trampoline, None)

    if not lib.rda_init(handle):
        lib.rda_config_free(handle)
        _engine._fail("the engine did not start")
    # Freed only after a successful start: rda_init copies what it needs, and freeing it
    # on the failure path above is what stops a refused start leaking one.
    lib.rda_config_free(handle)
    _config_handle = None


def load_interface(blueprint, source=""):
    """Shows a compiled layout (.rdab), replacing whatever was showing.

    `source` is the .tsx it came from. Where the build can compile one, naming it is what
    lets the engine reload the interface when the file changes.
    """
    from . import _engine
    lib = _engine.load()
    if not lib.rda_load_interface(str(blueprint).encode("utf-8"),
                                  str(source).encode("utf-8")):
        _engine._fail("cannot load {!r}".format(blueprint))


def open_routes(routes, layout_dir, source_dir=""):
    """Shows a set of screens, one at a time, with `state.route` naming which.

    `routes` is the ROUTES table a generated state module exports -- a mapping of name to
    {"layout": ..., "params": (...)}, in the order they were declared, because the first
    one is where the application opens unless `state.route` already says otherwise.

    After this, navigating is an ordinary write::

        State.route = "catalogue"

    which is the same sentence the interface itself uses, because "which screen is
    showing" is state and this engine has one answer for state.
    """
    import ctypes
    from . import _engine

    lib = _engine.load()
    names, layouts, params = [], [], []
    for name, route in routes.items():
        names.append(str(name).encode("utf-8"))
        if isinstance(route, str):        # {"home": "hello"}, the short spelling
            layouts.append(route.encode("utf-8"))
            params.append(b"")
        else:
            layouts.append(str(route["layout"]).encode("utf-8"))
            params.append(",".join(route.get("params") or ()).encode("utf-8"))
    if not names:
        raise RdaError("no routes to open")

    count = len(names)
    block = ctypes.c_char_p * count
    if not lib.rda_open_routes(block(*names), block(*layouts), block(*params), count,
                               str(layout_dir).encode("utf-8"),
                               str(source_dir).encode("utf-8")):
        _engine._fail("cannot open the screens")


def set_transition_ms(ms):
    """How long one screen takes to cross-fade into the next. Zero is an instant swap."""
    from . import _engine
    _engine.load().rda_set_transition_ms(float(ms))


def back():
    """One step back through the screens. False when there is nowhere to go."""
    from . import _engine
    return bool(_engine.load().rda_route_back())


def forward():
    """One step forward again. False when there is nowhere to go."""
    from . import _engine
    return bool(_engine.load().rda_route_forward())


def can_go_back():
    from . import _engine
    return bool(_engine.load().rda_route_can_go_back())


def can_go_forward():
    from . import _engine
    return bool(_engine.load().rda_route_can_go_forward())


def running():
    """Whether the window is still open."""
    from . import _engine
    return bool(_engine.load().rda_running())


def stop():
    """Asks the engine to close. Safe from any thread, and before init()."""
    from . import _engine
    _engine.load().rda_stop()


def wait():
    """Blocks until the engine has stopped and its thread has been joined."""
    from . import _engine
    _engine.load().rda_wait()


def dropped_files():
    """Every file let go over the window since the last call, as a list of paths.

    Empty most of the time. Ask on the same beat as everything else -- a drop is queued
    rather than delivered, so nothing is lost between one look and the next.
    """
    from ctypes import create_string_buffer
    lib = _engine.load()
    paths = []
    buffer = create_string_buffer(4096)
    while True:
        answer = lib.rda_poll_dropped_file(buffer, 4096)
        if answer <= 0:
            break
        paths.append(buffer.value.decode("utf-8", "replace"))
    return paths


def define_image(name, data):
    """Registers a picture a backend made, under `name`.

    `data` is an encoded image -- PNG, JPEG, BMP, TGA, GIF, PSD, HDR, PNM -- as bytes.
    A layout shows it with `src="mem:<name>"`.

    Registering the same name again replaces what every <image> naming it draws, which is
    what makes this the shape a preview wants. The bytes are copied, so the caller may let
    them go as soon as this returns.
    """
    from ctypes import c_char_p
    payload = bytes(data)
    if not payload:
        # Raised rather than _fail'd: _fail appends the engine's last error, and the
        # engine has not been asked anything yet, so what it would append belongs to
        # whatever was called before this.
        raise _engine.RdaError("there are no bytes to make an image from")
    if not _engine.load().rda_image_define(str(name).encode("utf-8"),
                                           c_char_p(payload), len(payload)):
        _engine._fail("cannot register the image '{}'".format(name))


def define_image_pixels(name, pixels, width, height):
    """The same, from raw pixels: four bytes each (R, G, B, A), rows tightly packed.

    `width * height * 4` bytes in all. For a buffer already in the right shape -- a numpy
    array's `.tobytes()`, a framebuffer -- where encoding it to PNG so the engine could
    decode it again would be a strange way to spend a millisecond.
    """
    from ctypes import c_char_p
    payload = bytes(pixels)
    wanted = int(width) * int(height) * 4
    if len(payload) < wanted:
        raise _engine.RdaError("a {}x{} image needs {} bytes, and there are {}"
                               .format(width, height, wanted, len(payload)))
    if not _engine.load().rda_image_define_pixels(str(name).encode("utf-8"),
                                                  c_char_p(payload),
                                                  int(width), int(height)):
        _engine._fail("cannot register the image '{}'".format(name))


def push_frame(name, data):
    """Pushes an encoded frame -- PNG, JPEG, and the rest -- into the stream `name`.

    A layout shows it with `<stream name="...">`. Unlike `define_image`, the surface is
    kept and written into, so a feed does not build a texture per frame.
    """
    from ctypes import c_char_p
    payload = bytes(data)
    if not payload:
        raise _engine.RdaError("there are no bytes to push")
    if not _engine.load().rda_stream_push_encoded(str(name).encode("utf-8"),
                                                  c_char_p(payload), len(payload)):
        _engine._fail("cannot push a frame into '{}'".format(name))


def push_frame_pixels(name, pixels, width, height):
    """The same, from raw pixels: four bytes each (R, G, B, A), rows tightly packed."""
    from ctypes import c_char_p
    payload = bytes(pixels)
    wanted = int(width) * int(height) * 4
    if len(payload) < wanted:
        raise _engine.RdaError("a {}x{} frame needs {} bytes, and there are {}"
                               .format(width, height, wanted, len(payload)))
    if not _engine.load().rda_stream_push(str(name).encode("utf-8"), c_char_p(payload),
                                          int(width), int(height)):
        _engine._fail("cannot push a frame into '{}'".format(name))


def stream_wanted(name):
    """Whether anybody is looking at this stream.

    False for one on a screen that is not showing. Ask before decoding the next frame:
    this is what stops a feed nobody can see from costing anything.
    """
    return _engine.load().rda_stream_wanted(str(name).encode("utf-8")) == 1


def stream_counts(name):
    """(pushed, shown) -- frames sent, and frames still current when something drew them.

    The gap is what is being wasted: pushing sixty a second into a window drawing thirty
    means half of them were replaced before anything sampled them.
    """
    from ctypes import c_int64, byref
    pushed, shown = c_int64(0), c_int64(0)
    _engine.load().rda_stream_counts(str(name).encode("utf-8"), byref(pushed), byref(shown))
    return pushed.value, shown.value


def close_stream(name):
    """Drops a stream. A <stream> naming it then draws nothing."""
    if not _engine.load().rda_stream_close(str(name).encode("utf-8")):
        _engine._fail("cannot close the stream '{}'".format(name))


def define_effect(name, glsl):
    """Compiles a filter and keeps it under `name`.

    Write the filter, not the Vulkan around it. `src` is the input, `store(c)` writes the
    result, and `uv()`, `coord()`, `size()` and `param(i)` say where you are and what you
    were passed:

        rda.define_effect("grey", GREY)   # GREY being the two lines below

        void main() {
            vec4 c = texture(src, uv());
            store(vec4(vec3(dot(c.rgb, vec3(0.2126, 0.7152, 0.0722))), c.a));
        }

    Colours inside an effect are linear light, not the sRGB a theme is written in -- which
    is the only space image arithmetic is correct in. GLSL beginning with `#version` is
    taken as a whole shader and nothing is prepended.

    Raises with the compiler's message, which names the line, if it will not build.
    """
    if not _engine.load().rda_effect_define(str(name).encode("utf-8"),
                                            str(glsl).encode("utf-8")):
        _engine._fail("cannot define the effect '{}'".format(name))


def apply_effect(name, source, into, params=()):
    """Runs the effect over `source` into the stream `into`.

    `source` is one stream's name, or a list of up to four. Several are reachable in the
    shader as `tap(0, at)` .. `tap(3, at)`, and `src` is the first:

        rda.apply_effect("blend", ["a", "b"], "mixed", [0.5])

    `into` is made if it is not there and re-made when the **first** source changes size;
    the rest are sampled in 0..1, so a mask of another size is resized rather than refused.
    It may not be one of the sources. `params` is up to eight floats, as `param(0..7)`.
    """
    from ctypes import c_char_p, c_float
    names = [source] if isinstance(source, str) else list(source)
    if not names:
        raise _engine.RdaError("an effect needs something to read")
    if len(names) > 4:
        raise _engine.RdaError(
            "{} sources, and a filter reads at most four. Chain two effects instead."
            .format(len(names)))
    values = [float(v) for v in params][:8]
    block = (c_float * len(values))(*values) if values else None
    encoded = [str(n).encode("utf-8") for n in names]
    block_names = (c_char_p * len(encoded))(*encoded)
    if not _engine.load().rda_effect_apply_many(str(name).encode("utf-8"),
                                                block_names, len(encoded),
                                                str(into).encode("utf-8"),
                                                block, len(values)):
        _engine._fail("cannot apply the effect '{}'".format(name))


def read_frame(name):
    """The current frame of a stream, as (pixels, width, height).

    RGBA8, rows tightly packed, and **as it looks on screen**: a surface an effect wrote
    holds linear light and is encoded on the way out, so saving this as a PNG gives a PNG
    of what was displayed.

    Costs a round trip to the GPU and a wait. Right for saving a frame or handing one to a
    model, wrong for doing every frame -- that is what <stream> is for.
    """
    from ctypes import c_char_p, c_int, byref, create_string_buffer
    lib = _engine.load()
    width, height = c_int(0), c_int(0)
    needed = lib.rda_stream_read(str(name).encode("utf-8"), None, 0,
                                 byref(width), byref(height))
    if needed < 0:
        _engine._fail("cannot read the stream '{}'".format(name))
    if needed == 0:
        return b"", 0, 0
    buffer = create_string_buffer(needed)
    got = lib.rda_stream_read(str(name).encode("utf-8"), buffer, needed,
                              byref(width), byref(height))
    if got < 0:
        _engine._fail("cannot read the stream '{}'".format(name))
    return buffer.raw[:needed], width.value, height.value


def forget_effect(name):
    """Drops a compiled effect."""
    if not _engine.load().rda_effect_forget(str(name).encode("utf-8")):
        _engine._fail("cannot forget the effect '{}'".format(name))


def forget_image(name):
    """Drops a registered picture. An <image> still naming it draws nothing."""
    if not _engine.load().rda_image_forget(str(name).encode("utf-8")):
        _engine._fail("cannot forget the image '{}'".format(name))


def focus(widget_id=""):
    """Puts the keyboard on a widget, by the full id its layout gave it.

    The path the log and the blueprint spell -- "root/composer", not "composer". Empty
    takes the keyboard away, which is what a click on nothing does.
    """
    if not _engine.load().rda_focus(str(widget_id).encode("utf-8")):
        _engine._fail("cannot focus '{}'".format(widget_id))


def _pick(call, *args):
    """The two-call shape, for a dialog that answers with a path."""
    from ctypes import create_string_buffer
    length = call(*args, None, 0)
    if length < 0:
        _engine._fail("cannot open the chooser")
    if length == 0:
        return None            # cancelled, which is an answer
    buffer = create_string_buffer(length + 1)
    call(*args, buffer, length + 1)
    return buffer.value.decode("utf-8", "replace")


def pick_folder(title="", start=""):
    """The platform's folder chooser. Returns the path, or None if it was cancelled.

    Blocks this thread until the reader answers -- the window goes on drawing behind it,
    because this is the one call that does not cross to the engine's loop.
    """
    lib = _engine.load()
    return _pick(lib.rda_pick_folder, str(title).encode("utf-8"), str(start).encode("utf-8"))


def pick_file(title="", start="", filter=""):
    """The platform's file chooser. `filter` is "Images|*.png;*.jpg"; empty means any."""
    lib = _engine.load()
    return _pick(lib.rda_pick_file, str(title).encode("utf-8"), str(start).encode("utf-8"),
                 str(filter).encode("utf-8"))


def set_title(text):
    """The window's title, after it has opened. `StartupConfig.name` sets the first one."""
    if not _engine.load().rda_set_title(str(text).encode("utf-8")):
        _engine._fail("cannot set the title")


def set_icon(path=""):
    """The window's icon, after it has opened.

    A .png, or an .svg -- which is drawn at every size an OS picks from, so one file
    covers the title bar, the alt-tab card and the taskbar. "" puts the platform's
    default back. `StartupConfig.icon` sets the first one.

    Not the executable's icon: that one is a resource inside the binary, put there when
    the program is built rather than when it runs.
    """
    if not _engine.load().rda_set_icon(str(path).encode("utf-8")):
        _engine._fail("cannot set the icon")


def set_clipboard(text):
    """Puts `text` on the OS clipboard."""
    if not _engine.load().rda_clipboard_set(str(text).encode("utf-8")):
        _engine._fail("cannot write the clipboard")


def clipboard():
    """What is on the OS clipboard, as text. Empty when it holds none."""
    from ctypes import create_string_buffer
    lib = _engine.load()
    length = lib.rda_clipboard_get(None, 0)
    if length < 0:
        _engine._fail("cannot read the clipboard")
    if length == 0:
        return ""
    buffer = create_string_buffer(length + 1)
    lib.rda_clipboard_get(buffer, length + 1)
    return buffer.value.decode("utf-8", "replace")


def measure_text(text, size=0.0):
    """(width, height) `text` would be drawn at, in the pixels a layout uses.

    `size` of 0 is the interface's own. This is what a backend that wraps text should
    ask instead of assuming a column count -- the wrap then follows the window and the
    font rather than a number somebody guessed.
    """
    from ctypes import byref, c_float
    # Rejected rather than stringified: str(None) is "None", four characters wide, and
    # silently measuring those is the kind of answer that is believed.
    if text is None:
        raise RdaError("measure_text() needs some text")
    width, height = c_float(0.0), c_float(0.0)
    if not _engine.load().rda_measure_text(str(text).encode("utf-8"), float(size),
                                           byref(width), byref(height)):
        _engine._fail("cannot measure text")
    return width.value, height.value


def set_theme(path):
    """Swaps the whole look while the window stays open.

    The compiled `.rdth` replaces what was there rather than layering on top, so a theme
    that does not mention a variant does not inherit the last one's. Colours and radii
    travel to their new values over the transitionMs the new theme gives them; a theme
    whose variants say 0 swaps instantly.
    """
    if not _engine.load().rda_set_theme(str(path).encode("utf-8")):
        _engine._fail("cannot use the theme '{}'".format(path))


def _color(value):
    """A colour as the engine packs them: 0xAABBGGRR.

    Accepts what a theme accepts -- "#RGB", "#RRGGBB", "#RRGGBBAA" -- so a drawing and
    the interface around it can be written in the same notation. An int passes through,
    already packed.
    """
    if isinstance(value, int):
        return value & 0xFFFFFFFF
    text = str(value).lstrip("#")
    if len(text) == 3:
        text = "".join(c * 2 for c in text)
    if len(text) == 6:
        text += "FF"
    if len(text) != 8:
        raise RdaError("a colour is #RGB, #RRGGBB or #RRGGBBAA, not {!r}".format(value))
    r, g, b, a = (int(text[i:i + 2], 16) for i in (0, 2, 4, 6))
    return r | (g << 8) | (b << 16) | (a << 24)


class Drawing:
    """What to draw in a <viewport>, in its own coordinates: 0,0 is its top-left corner.

    Built up here and sent in one call, because every call into the engine crosses to its
    loop thread and waits -- a shape at a time would be a frame at a time. The list stays
    on screen until another one replaces it, so a drawing that does not change is drawn
    once and then costs nothing.

        d = rda.Drawing()
        d.clear("#11141A")
        for i, value in enumerate(values):
            d.rect(i * 12, height - value, 8, value, "#3A6AD0", radius=2)
        rda.draw("chart", d)
    """

    def __init__(self):
        self._commands = []

    def __len__(self):
        return len(self._commands)

    def clear(self, color):
        """Fills the whole viewport, whatever size it turned out to be."""
        self._add(_engine.DRAW_CLEAR, color)
        return self

    def rect(self, x, y, w, h, color, radius=0.0):
        self._add(_engine.DRAW_RECT, color, x, y, w, h, radius)
        return self

    def circle(self, x, y, radius, color):
        """A rect with equal sides and a radius of half of them. Centred on x, y."""
        self._add(_engine.DRAW_RECT, color, x - radius, y - radius,
                  radius * 2, radius * 2, radius)
        return self

    def line(self, x1, y1, x2, y2, color, width=1.0):
        self._add(_engine.DRAW_LINE, color, x1, y1, x2, y2, width)
        return self

    def text(self, x, y, text, color, size=0.0):
        """Top-left at x, y. A size of 0 is the interface's own, and the sizes that draw
        crisply are the ones the atlas was baked with."""
        self._add(_engine.DRAW_TEXT, color, x, y, 0.0, 0.0, size, text)
        return self

    def _add(self, op, color, a=0.0, b=0.0, c=0.0, d=0.0, e=0.0, text=None):
        command = _engine.DrawCmd()
        command.op = op
        command.color = _color(color)
        command.a, command.b, command.c, command.d, command.e = (
            float(a), float(b), float(c), float(d), float(e))
        if text is not None:
            # Kept alive on the command: ctypes stores the pointer, and the engine copies
            # it on the other side, but the bytes have to survive until it does.
            command._keep = str(text).encode("utf-8")
            command.text = command._keep
        self._commands.append(command)


def draw(name, drawing):
    """Puts `drawing` in the <viewport name="..."> and leaves it there.

    An empty Drawing takes it back down; a viewport nothing has ever drawn into shows the
    engine's own 3D scene instead, which is what this element used to be for.
    """
    commands = getattr(drawing, "_commands", None)
    if commands is None:
        raise TypeError("draw() takes a Drawing")
    count = len(commands)
    block = (_engine.DrawCmd * count)(*commands) if count else None
    if not _engine.load().rda_viewport_draw(name.encode("utf-8"), block, count):
        _engine._fail("cannot draw in '{}'".format(name))


def viewport_size(name="main"):
    """(width, height) in the pixels a drawing uses, or (0, 0) before a frame placed it."""
    from ctypes import byref, c_float
    width, height = c_float(0.0), c_float(0.0)
    if not _engine.load().rda_viewport_size(name.encode("utf-8"), byref(width), byref(height)):
        _engine._fail("cannot measure '{}'".format(name))
    return width.value, height.value
