"""rda -- write a RendeerAlpha backend in Python.

    import rda
    from state import State, Commands       # generated by `rda python`

    config = rda.StartupConfig()
    config.name = "My application"
    config.theme = "res/themes/app.rdth"

    @config.on_start
    def opened():
        rda.load_interface("res/layouts/home.rdab")
        State.count = 0

    @Commands.add_one
    def add_one():
        State.count += 1

    rda.init(config)
    rda.wait()

Python is a *backend* here, which is what the engine is for. The interface is a compiled
layout -- written in TSX, checked against a generated schema, styled by a theme, bound to
signals and animated by the engine. Python does not draw it; it loads it, writes the state
it reads, and answers the work it asks for. That is the same job C++ has, and the layout
cannot tell which of them is behind it.

There is no extension module to build. The engine is a shared library and this package is
a description of it, so `pip install` has nothing to compile and nothing to go wrong.

---- threading ----

`init()` starts the engine on a thread of its own and returns once it is up -- the window,
the renderer and your on_start all finished -- so the interpreter stays yours and the line
after it may write state. A REPL, a web server or a data pipeline can carry on while a
window is open. Call `wait()` when there is nothing left to do but let the window live.

Every call in this package is safe from any thread. The engine's state belongs to its loop
thread, so each call hands its work over and waits -- which costs a frame, and is the
right price for a backend. Handlers run on the loop thread; calls made from inside one are
free.
"""

from . import _engine
from ._engine import RdaError, bind_command, invoke, load

__all__ = [
    "StartupConfig", "RdaError", "Drawing",
    "init", "stop", "wait", "running", "load_interface", "bind_command", "invoke", "load",
    "open_routes", "set_transition_ms", "back", "forward",
    "can_go_back", "can_go_forward",
    "draw", "viewport_size", "set_theme",
]


class StartupConfig:
    """What the engine needs to start.

    The callbacks are decorators as well as attributes, because a handler reads better
    where it is written than in an assignment three lines further down:

        @config.on_start
        def opened():
            ...
    """

    __slots__ = ("name", "theme", "languages", "vsync", "font", "font_height",
                 "_on_start", "_on_update", "_on_shutdown")

    def __init__(self):
        self.name = "RendeerAlpha"
        self.theme = ""       # a compiled .rdth; empty keeps the built-in look
        self.languages = ""   # res/themes/languages.xml, for syntax highlighting
        self.vsync = True
        self.font = ""        # a .ttf; empty keeps the engine's own
        self.font_height = 0  # pixels for body text; 0 keeps the default
        self._on_start = None
        self._on_update = None
        self._on_shutdown = None

    def on_start(self, fn):
        """Once, after the window is up. Load the interface here."""
        self._on_start = fn
        return fn

    def on_update(self, fn):
        """Once per frame, before it is drawn. Takes the seconds since the last one."""
        self._on_update = fn
        return fn

    def on_shutdown(self, fn):
        """Once, after the loop ends."""
        self._on_shutdown = fn
        return fn


_config_handle = None


def init(config=None):
    """Starts the engine and returns once it is up.

    Up means the window, the renderer and your on_start have all finished -- so the line
    after this one may write state and expect it to exist. The engine itself runs on a
    thread of its own, which is why this returns at all.

    Raises RdaError if it did not start, or if on_start stopped it.
    """
    global _config_handle
    from . import _engine

    lib = _engine.load()
    config = config or StartupConfig()

    handle = lib.rda_config_new()
    if not handle:
        raise RdaError("cannot allocate a config")
    lib.rda_config_set_name(handle, str(config.name).encode("utf-8"))
    if config.theme:
        lib.rda_config_set_theme(handle, str(config.theme).encode("utf-8"))
    if config.languages:
        lib.rda_config_set_languages(handle, str(config.languages).encode("utf-8"))
    lib.rda_config_set_vsync(handle, 1 if config.vsync else 0)
    if config.font or config.font_height:
        lib.rda_config_set_font(handle, str(config.font).encode("utf-8"),
                                float(config.font_height))

    # Held for the life of the process for the same reason a command handler is: the
    # engine calls these long after this function has returned.
    # on_start is always registered, whether or not the application wanted one: it is
    # also where handlers bound at import time are applied, and they can only be applied
    # after the application has declared the commands they name.
    def _started(_user):
        if config._on_start:
            config._on_start()
        _engine.flush_pending()

    trampoline = _engine._Callback(_started)
    _engine._alive.append(trampoline)
    lib.rda_config_on_start(handle, trampoline, None)
    if config._on_update:
        trampoline = _engine._UpdateCallback(lambda dt, _user: config._on_update(dt))
        _engine._alive.append(trampoline)
        lib.rda_config_on_update(handle, trampoline, None)
    if config._on_shutdown:
        trampoline = _engine._Callback(lambda _user: config._on_shutdown())
        _engine._alive.append(trampoline)
        lib.rda_config_on_shutdown(handle, trampoline, None)

    if not lib.rda_init(handle):
        lib.rda_config_free(handle)
        _engine._fail("the engine did not start")
    # Freed only after a successful start: rda_init copies what it needs, and freeing it
    # on the failure path above is what stops a refused start leaking one.
    lib.rda_config_free(handle)
    _config_handle = None


def load_interface(blueprint, source=""):
    """Shows a compiled layout (.rdab), replacing whatever was showing.

    `source` is the .tsx it came from. Where the build can compile one, naming it is what
    lets the engine reload the interface when the file changes.
    """
    from . import _engine
    lib = _engine.load()
    if not lib.rda_load_interface(str(blueprint).encode("utf-8"),
                                  str(source).encode("utf-8")):
        _engine._fail("cannot load {!r}".format(blueprint))


def open_routes(routes, layout_dir, source_dir=""):
    """Shows a set of screens, one at a time, with `state.route` naming which.

    `routes` is the ROUTES table a generated state module exports -- a mapping of name to
    {"layout": ..., "params": (...)}, in the order they were declared, because the first
    one is where the application opens unless `state.route` already says otherwise.

    After this, navigating is an ordinary write::

        State.route = "catalogue"

    which is the same sentence the interface itself uses, because "which screen is
    showing" is state and this engine has one answer for state.
    """
    import ctypes
    from . import _engine

    lib = _engine.load()
    names, layouts, params = [], [], []
    for name, route in routes.items():
        names.append(str(name).encode("utf-8"))
        if isinstance(route, str):        # {"home": "hello"}, the short spelling
            layouts.append(route.encode("utf-8"))
            params.append(b"")
        else:
            layouts.append(str(route["layout"]).encode("utf-8"))
            params.append(",".join(route.get("params") or ()).encode("utf-8"))
    if not names:
        raise RdaError("no routes to open")

    count = len(names)
    block = ctypes.c_char_p * count
    if not lib.rda_open_routes(block(*names), block(*layouts), block(*params), count,
                               str(layout_dir).encode("utf-8"),
                               str(source_dir).encode("utf-8")):
        _engine._fail("cannot open the screens")


def set_transition_ms(ms):
    """How long one screen takes to cross-fade into the next. Zero is an instant swap."""
    from . import _engine
    _engine.load().rda_set_transition_ms(float(ms))


def back():
    """One step back through the screens. False when there is nowhere to go."""
    from . import _engine
    return bool(_engine.load().rda_route_back())


def forward():
    """One step forward again. False when there is nowhere to go."""
    from . import _engine
    return bool(_engine.load().rda_route_forward())


def can_go_back():
    from . import _engine
    return bool(_engine.load().rda_route_can_go_back())


def can_go_forward():
    from . import _engine
    return bool(_engine.load().rda_route_can_go_forward())


def running():
    """Whether the window is still open."""
    from . import _engine
    return bool(_engine.load().rda_running())


def stop():
    """Asks the engine to close. Safe from any thread, and before init()."""
    from . import _engine
    _engine.load().rda_stop()


def wait():
    """Blocks until the engine has stopped and its thread has been joined."""
    from . import _engine
    _engine.load().rda_wait()


def set_theme(path):
    """Swaps the whole look while the window stays open.

    The compiled `.rdth` replaces what was there rather than layering on top, so a theme
    that does not mention a variant does not inherit the last one's. Colours and radii
    travel to their new values over the transitionMs the new theme gives them; a theme
    whose variants say 0 swaps instantly.
    """
    if not _engine.load().rda_set_theme(str(path).encode("utf-8")):
        _engine._fail("cannot use the theme '{}'".format(path))


def _color(value):
    """A colour as the engine packs them: 0xAABBGGRR.

    Accepts what a theme accepts -- "#RGB", "#RRGGBB", "#RRGGBBAA" -- so a drawing and
    the interface around it can be written in the same notation. An int passes through,
    already packed.
    """
    if isinstance(value, int):
        return value & 0xFFFFFFFF
    text = str(value).lstrip("#")
    if len(text) == 3:
        text = "".join(c * 2 for c in text)
    if len(text) == 6:
        text += "FF"
    if len(text) != 8:
        raise RdaError("a colour is #RGB, #RRGGBB or #RRGGBBAA, not {!r}".format(value))
    r, g, b, a = (int(text[i:i + 2], 16) for i in (0, 2, 4, 6))
    return r | (g << 8) | (b << 16) | (a << 24)


class Drawing:
    """What to draw in a <viewport>, in its own coordinates: 0,0 is its top-left corner.

    Built up here and sent in one call, because every call into the engine crosses to its
    loop thread and waits -- a shape at a time would be a frame at a time. The list stays
    on screen until another one replaces it, so a drawing that does not change is drawn
    once and then costs nothing.

        d = rda.Drawing()
        d.clear("#11141A")
        for i, value in enumerate(values):
            d.rect(i * 12, height - value, 8, value, "#3A6AD0", radius=2)
        rda.draw("chart", d)
    """

    def __init__(self):
        self._commands = []

    def __len__(self):
        return len(self._commands)

    def clear(self, color):
        """Fills the whole viewport, whatever size it turned out to be."""
        self._add(_engine.DRAW_CLEAR, color)
        return self

    def rect(self, x, y, w, h, color, radius=0.0):
        self._add(_engine.DRAW_RECT, color, x, y, w, h, radius)
        return self

    def circle(self, x, y, radius, color):
        """A rect with equal sides and a radius of half of them. Centred on x, y."""
        self._add(_engine.DRAW_RECT, color, x - radius, y - radius,
                  radius * 2, radius * 2, radius)
        return self

    def line(self, x1, y1, x2, y2, color, width=1.0):
        self._add(_engine.DRAW_LINE, color, x1, y1, x2, y2, width)
        return self

    def text(self, x, y, text, color, size=0.0):
        """Top-left at x, y. A size of 0 is the interface's own, and the sizes that draw
        crisply are the ones the atlas was baked with."""
        self._add(_engine.DRAW_TEXT, color, x, y, 0.0, 0.0, size, text)
        return self

    def _add(self, op, color, a=0.0, b=0.0, c=0.0, d=0.0, e=0.0, text=None):
        command = _engine.DrawCmd()
        command.op = op
        command.color = _color(color)
        command.a, command.b, command.c, command.d, command.e = (
            float(a), float(b), float(c), float(d), float(e))
        if text is not None:
            # Kept alive on the command: ctypes stores the pointer, and the engine copies
            # it on the other side, but the bytes have to survive until it does.
            command._keep = str(text).encode("utf-8")
            command.text = command._keep
        self._commands.append(command)


def draw(name, drawing):
    """Puts `drawing` in the <viewport name="..."> and leaves it there.

    An empty Drawing takes it back down; a viewport nothing has ever drawn into shows the
    engine's own 3D scene instead, which is what this element used to be for.
    """
    commands = getattr(drawing, "_commands", None)
    if commands is None:
        raise TypeError("draw() takes a Drawing")
    count = len(commands)
    block = (_engine.DrawCmd * count)(*commands) if count else None
    if not _engine.load().rda_viewport_draw(name.encode("utf-8"), block, count):
        _engine._fail("cannot draw in '{}'".format(name))


def viewport_size(name="main"):
    """(width, height) in the pixels a drawing uses, or (0, 0) before a frame placed it."""
    from ctypes import byref, c_float
    width, height = c_float(0.0), c_float(0.0)
    if not _engine.load().rda_viewport_size(name.encode("utf-8"), byref(width), byref(height)):
        _engine._fail("cannot measure '{}'".format(name))
    return width.value, height.value
